// This file was auto-generated by the veyron vdl tool.
// Source: errors.vdl

package ipc

import (
	// VDL system imports
	"v.io/core/veyron2/context"
	"v.io/core/veyron2/i18n"
	"v.io/core/veyron2/verror2"

	// VDL user imports
	"v.io/core/veyron2/security"
)

var (
	InvalidBlessings = verror2.Register("v.io/core/veyron/runtimes/google/ipc.InvalidBlessings", verror2.NoRetry, "{1:}{2:} All valid blessings for this request: {3} (rejected {4}) are disallowed by the policy {5} (rejected {6})")
)

func init() {
	i18n.Cat().SetWithBase(i18n.LangID("en"), i18n.MsgID(InvalidBlessings.ID), "{1:}{2:} All valid blessings for this request: {3} (rejected {4}) are disallowed by the policy {5} (rejected {6})")
}

// MakeInvalidBlessings returns an error with the InvalidBlessings ID.
func MakeInvalidBlessings(ctx *context.T, remote []string, remoteErr []security.RejectedBlessing, local []string, localErr []security.RejectedBlessing) error {
	return verror2.Make(InvalidBlessings, ctx, remote, remoteErr, local, localErr)
}
