package fortune

import "veyron2/security"

// Fortune allows clients to Get and Add fortune strings.
type Fortune interface {
 // Get returns a random fortune.
 Get() (Fortune string, Err error) {security.ReadLabel}
 // Add stores a fortune in the set used by Get.
 Add(Fortune string) error {security.WriteLabel}
}
