// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was auto-generated by the vanadium vdl tool.
// Source: browspr.vdl

package browspr

import (
	"v.io/v23/vdl"
	"v.io/x/ref/services/identity"
	"v.io/x/ref/services/wspr/internal/account"
)

type StartMessage struct {
	CleanupBlessings      bool
	Identityd             string
	IdentitydBlessingRoot identity.BlessingRootResponse
	Proxy                 string
	NamespaceRoot         string
	LogLevel              int32
	LogModule             string
}

func (StartMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.StartMessage"`
}) {
}

func (m *StartMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_StartMessage == nil || __VDLTypebrowspr0 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("CleanupBlessings")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromBool(bool(m.CleanupBlessings), vdl.BoolType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	keyTarget4, fieldTarget5, err := fieldsTarget1.StartField("Identityd")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget5.FromString(string(m.Identityd), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget4, fieldTarget5); err != nil {
			return err
		}
	}
	keyTarget6, fieldTarget7, err := fieldsTarget1.StartField("IdentitydBlessingRoot")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {

		if err := m.IdentitydBlessingRoot.FillVDLTarget(fieldTarget7, __VDLType_browspr_v_io_x_ref_services_identity_BlessingRootResponse); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget6, fieldTarget7); err != nil {
			return err
		}
	}
	keyTarget8, fieldTarget9, err := fieldsTarget1.StartField("Proxy")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget9.FromString(string(m.Proxy), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget8, fieldTarget9); err != nil {
			return err
		}
	}
	keyTarget10, fieldTarget11, err := fieldsTarget1.StartField("NamespaceRoot")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget11.FromString(string(m.NamespaceRoot), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget10, fieldTarget11); err != nil {
			return err
		}
	}
	keyTarget12, fieldTarget13, err := fieldsTarget1.StartField("LogLevel")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget13.FromInt(int64(m.LogLevel), vdl.Int32Type); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget12, fieldTarget13); err != nil {
			return err
		}
	}
	keyTarget14, fieldTarget15, err := fieldsTarget1.StartField("LogModule")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget15.FromString(string(m.LogModule), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget14, fieldTarget15); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *StartMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type AssociateAccountMessage struct {
	Account string
	Origin  string
	Caveats []account.Caveat
}

func (AssociateAccountMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.AssociateAccountMessage"`
}) {
}

func (m *AssociateAccountMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_AssociateAccountMessage == nil || __VDLTypebrowspr1 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("Account")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromString(string(m.Account), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	keyTarget4, fieldTarget5, err := fieldsTarget1.StartField("Origin")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget5.FromString(string(m.Origin), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget4, fieldTarget5); err != nil {
			return err
		}
	}
	keyTarget6, fieldTarget7, err := fieldsTarget1.StartField("Caveats")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {

		listTarget8, err := fieldTarget7.StartList(__VDLTypebrowspr2, len(m.Caveats))
		if err != nil {
			return err
		}
		for i, elem10 := range m.Caveats {
			elemTarget9, err := listTarget8.StartElem(i)
			if err != nil {
				return err
			}

			if err := elem10.FillVDLTarget(elemTarget9, __VDLType_browspr_v_io_x_ref_services_wspr_internal_account_Caveat); err != nil {
				return err
			}
			if err := listTarget8.FinishElem(elemTarget9); err != nil {
				return err
			}
		}
		if err := fieldTarget7.FinishList(listTarget8); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget6, fieldTarget7); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *AssociateAccountMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type CreateAccountMessage struct {
	Token string
}

func (CreateAccountMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.CreateAccountMessage"`
}) {
}

func (m *CreateAccountMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CreateAccountMessage == nil || __VDLTypebrowspr3 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("Token")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromString(string(m.Token), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *CreateAccountMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type CleanupMessage struct {
	InstanceId int32
}

func (CleanupMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.CleanupMessage"`
}) {
}

func (m *CleanupMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CleanupMessage == nil || __VDLTypebrowspr4 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("InstanceId")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromInt(int64(m.InstanceId), vdl.Int32Type); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *CleanupMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type OriginHasAccountMessage struct {
	Origin string
}

func (OriginHasAccountMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.OriginHasAccountMessage"`
}) {
}

func (m *OriginHasAccountMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_OriginHasAccountMessage == nil || __VDLTypebrowspr5 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("Origin")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromString(string(m.Origin), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *OriginHasAccountMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type GetAccountsMessage struct {
}

func (GetAccountsMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.GetAccountsMessage"`
}) {
}

func (m *GetAccountsMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_GetAccountsMessage == nil || __VDLTypebrowspr6 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *GetAccountsMessage) MakeVDLTarget() vdl.Target {
	return nil
}

type CreateInstanceMessage struct {
	InstanceId     int32
	Origin         string
	NamespaceRoots []string
	Proxy          string
}

func (CreateInstanceMessage) __VDLReflect(struct {
	Name string `vdl:"v.io/x/ref/services/wspr/internal/browspr.CreateInstanceMessage"`
}) {
}

func (m *CreateInstanceMessage) FillVDLTarget(t vdl.Target, tt *vdl.Type) error {

	if __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CreateInstanceMessage == nil || __VDLTypebrowspr7 == nil {
		panic("Initialization order error: types generated for FillVDLTarget not initialized. Consider moving caller to an init() block.")
	}
	fieldsTarget1, err := t.StartFields(tt)
	if err != nil {
		return err
	}

	keyTarget2, fieldTarget3, err := fieldsTarget1.StartField("InstanceId")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget3.FromInt(int64(m.InstanceId), vdl.Int32Type); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget2, fieldTarget3); err != nil {
			return err
		}
	}
	keyTarget4, fieldTarget5, err := fieldsTarget1.StartField("Origin")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget5.FromString(string(m.Origin), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget4, fieldTarget5); err != nil {
			return err
		}
	}
	keyTarget6, fieldTarget7, err := fieldsTarget1.StartField("NamespaceRoots")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {

		listTarget8, err := fieldTarget7.StartList(__VDLTypebrowspr8, len(m.NamespaceRoots))
		if err != nil {
			return err
		}
		for i, elem10 := range m.NamespaceRoots {
			elemTarget9, err := listTarget8.StartElem(i)
			if err != nil {
				return err
			}
			if err := elemTarget9.FromString(string(elem10), vdl.StringType); err != nil {
				return err
			}
			if err := listTarget8.FinishElem(elemTarget9); err != nil {
				return err
			}
		}
		if err := fieldTarget7.FinishList(listTarget8); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget6, fieldTarget7); err != nil {
			return err
		}
	}
	keyTarget11, fieldTarget12, err := fieldsTarget1.StartField("Proxy")
	if err != vdl.ErrFieldNoExist && err != nil {
		return err
	}
	if err != vdl.ErrFieldNoExist {
		if err := fieldTarget12.FromString(string(m.Proxy), vdl.StringType); err != nil {
			return err
		}
		if err := fieldsTarget1.FinishField(keyTarget11, fieldTarget12); err != nil {
			return err
		}
	}
	if err := t.FinishFields(fieldsTarget1); err != nil {
		return err
	}
	return nil
}

func (m *CreateInstanceMessage) MakeVDLTarget() vdl.Target {
	return nil
}

func init() {
	vdl.Register((*StartMessage)(nil))
	vdl.Register((*AssociateAccountMessage)(nil))
	vdl.Register((*CreateAccountMessage)(nil))
	vdl.Register((*CleanupMessage)(nil))
	vdl.Register((*OriginHasAccountMessage)(nil))
	vdl.Register((*GetAccountsMessage)(nil))
	vdl.Register((*CreateInstanceMessage)(nil))
}

var __VDLTypebrowspr1 *vdl.Type = vdl.TypeOf((*AssociateAccountMessage)(nil))
var __VDLTypebrowspr4 *vdl.Type = vdl.TypeOf((*CleanupMessage)(nil))
var __VDLTypebrowspr3 *vdl.Type = vdl.TypeOf((*CreateAccountMessage)(nil))
var __VDLTypebrowspr7 *vdl.Type = vdl.TypeOf((*CreateInstanceMessage)(nil))
var __VDLTypebrowspr6 *vdl.Type = vdl.TypeOf((*GetAccountsMessage)(nil))
var __VDLTypebrowspr5 *vdl.Type = vdl.TypeOf((*OriginHasAccountMessage)(nil))
var __VDLTypebrowspr0 *vdl.Type = vdl.TypeOf((*StartMessage)(nil))
var __VDLTypebrowspr8 *vdl.Type = vdl.TypeOf([]string(nil))
var __VDLTypebrowspr2 *vdl.Type = vdl.TypeOf([]account.Caveat(nil))
var __VDLType_browspr_v_io_x_ref_services_identity_BlessingRootResponse *vdl.Type = vdl.TypeOf(identity.BlessingRootResponse{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_account_Caveat *vdl.Type = vdl.TypeOf(account.Caveat{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_AssociateAccountMessage *vdl.Type = vdl.TypeOf(AssociateAccountMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CleanupMessage *vdl.Type = vdl.TypeOf(CleanupMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CreateAccountMessage *vdl.Type = vdl.TypeOf(CreateAccountMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_CreateInstanceMessage *vdl.Type = vdl.TypeOf(CreateInstanceMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_GetAccountsMessage *vdl.Type = vdl.TypeOf(GetAccountsMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_OriginHasAccountMessage *vdl.Type = vdl.TypeOf(OriginHasAccountMessage{})
var __VDLType_browspr_v_io_x_ref_services_wspr_internal_browspr_StartMessage *vdl.Type = vdl.TypeOf(StartMessage{})

func __VDLEnsureNativeBuilt_browspr() {
}
